config/routes.rb
MotivationdashboardCom::Application.routes.draw do
  
  root :to => "pages#home"
  get 'features', :to => "pages#features"
  get 'pricing', :to => "pages#pricing"

  resources :users do
    get :reset_api_key
  end
  resources :user_session
  resources :widget_templates
  match '/logout' => 'user_sessions#destroy', :as => :logout
  match '/forgot_password' => 'password_resets#new', :as => :forgot_password
  match '/reset_password/:perishable_token' => 'password_resets#edit', :as => :reset_password
  resources :password_resets

  resources :widgets
  resources :data_sources  
  
  resource :dashboard
  
  namespace :setup do
    root :to => "data_sources#index"
    resources :data_sources do
      collection do
        get :auth_receive
      end
      resources :data_sets do
        resources :reports do
          resources :widgets
        end
      end
    end
  end
  
  namespace :integrations do
    
    resources :github do
      collection do
        post 'post_receive_hook'
      end
    end
    
  end
  
  namespace :big_brother do
    root :to => "pages#index"
    resources :users do
      collection do
        get :search
      end
    end
    resources :subscribers
  end
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic 
  
  before_save :set_default_next_poll
  
  has_one :dashboard
  has_many :data_sources
  
  before_create :set_api_key

  def set_api_key
    self.api_key = SecureRandom.hex(20)
  end

  def full_name
    "#{first_name} #{last_name}"
  end
  
  # Ugh, I hate this naming - Nathan 12:07AM SAT
  def user_bar_name
    full_name.blank? ? email : full_name
  end
  
  def self.find_by_email_and_send_reset_instructions(email)
    user = self.find_by_email(email)
    UserMailer.password_reset_instructions(user).deliver if user
  end
  
  def self.new_user_session_or_new_user(params)
    existing_user = self.find_by_email(params[:email])
    
    if existing_user
      user_session = UserSession.new(params)
    else
      params[:password_confirmation] = params[:password]
      self.new(params)
    end
  end
  
  def set_default_next_poll
    self.next_poll_at ||= 1.minute.from_now.utc
  end
  
  # punt the next_poll_at date to some time in the future.
  def punt_polling!
    if last_request_at > 5.minutes.ago.utc
      update_attribute(:next_poll_at, 30.seconds.from_now.utc)
    elsif last_request_at > 30.minutes.ago.utc
      update_attribute(:next_poll_at, 2.minutes.from_now.utc)
    elsif last_request_at > 2.hours.ago.utc
      update_attribute(:next_poll_at, 5.minutes.from_now.utc)
    else
      update_attribute(:next_poll_at, 1.hour.from_now.utc)
    end
  end
  
  def set_next_poll_at!
    update_attribute(:next_poll_at, Time.now.utc.to_s(:db))
  end

end

app/controllers/big_brother/users_controller.rb
class BigBrother::UsersController < BigBrother::ApplicationController
    
  def index
    @users = User.paginate(:per_page => 50, :page => params[:page], :order => 'users.last_name ASC')
  end
  
  def search
    # TODO - Refactor me, this is tad bit FUUUUGGGGLLLY . Nathan - 28th Oct 2010
    s = params[:search].split(' ')
    @users = User.paginate(:per_page => 50, :page => params[:page], :conditions => ['first_name LIKE ? OR first_name LIKE ? OR last_name LIKE ? OR last_name LIKE ? OR id LIKE ? OR email LIKE ?', "%#{s[0]}%", "%#{s[-1]}%", "%#{s[0]}%", "%#{s[-1]}%", params[:search], params[:search]], :order => 'users.last_name ASC')
  end  
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated profile for '#{@user.user_bar_name}'."
      redirect_to [:big_brother, :users]
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      flash[:notice] = "Successfully permanently removed '#{@user.user_bar_name}'."
    else
      flash[:error] = "Failed to permanently remove '#{@user.user_bar_name}'."
    end
    
    redirect_to [:big_brother, :users]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]
  layout :determine_layout

  def create
    @user = User.new_user_session_or_new_user(params[:user] || params[:user_session])
    
    if @user.save
      redirect_to dashboard_path
    else
      @subscriber = Subscriber.new
      render :action => 'pages/home'
    end
  end
  
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end
  
  def update
    params[:user][:password], params[:user][:password_confirmation] = nil, nil unless params[:change_password]

    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to user_path(@user)
    else
      render :action => :edit
    end
  end
  
  def reset_api_key
    current_user.api_key = SecureRandom.hex(20)
    if current_user.save
      flash[:notice] = "Your API Key has been reset to " + current_user.api_key
    else
      flash[:error] = "Could not update your API Key at this time."
    end
    redirect_to user_path(current_user)
  end
  
  private
  
  # Apparently, you can't specify layout multiple times :-( Nathan 12:49AM SAT
  def determine_layout
    action_name == 'create' ? 'application' : 'dashboard'
  end  
end

app/views/users/edit.html.haml
.data_source_title
  %h2
    Edit Your Details
.data_source_form
  - form_for @user do |f|
    %ul
      %li
        %label  
          First Name
        = f.text_field :first_name, :class => :text
      %li
        %label
          Last Name
        = f.text_field :last_name, :class => :text
      %li
        %label
          Email
        = f.text_field :email, :class => :text

      %li
        %label
          Phone
        = f.text_field :phone_number, :class => :text
  
      %li
        %label
          Twitter Username
        = f.text_field :twitter_username, :class => :text
      
      %li
        %label
          Change Your Password?
        = radio_button_tag :change_password, '1', params[:change_password] == '1', :onclick => "$('.change_password').slideDown();"
        Yes
        = radio_button_tag :change_password, '0', params[:change_password] != '1', :onclick => "$('.change_password').slideUp();"
        No 
      %li.change_password{:style => params[:change_password] == '1' ? '' : 'display: none;'}
        %label Password
        = f.password_field :password, :class => :text
      %li.change_password{:style => params[:change_password] == '1' ? '' : 'display: none;'}
        %label  Confirm Password
        = f.password_field :password_confirmation, :class => :text
      %li
        = f.submit 'Update Account', :disable_with => 'Updating Account ...'
        |
        = link_to 'Cancel', user_path(@user)

app/views/users/show.html.haml
.data_source_title
  %h2
    Your Details
    = link_to 'Edit', edit_user_path

.data_source_form
  %ul.no_bullets
    %li
      %strong First Name:
      = not_set(current_user.first_name)
    %li
      %strong Last Name:
      = not_set(current_user.last_name)
    %li
      %strong Email:
      = current_user.email
    %li
      %strong Phone Number:
      = not_set(current_user.phone_number)
    %li
      %strong Twitter Username:
      = not_set(current_user.twitter_username)
    %li
      %strong API Key:
      = not_set(current_user.api_key)
      = raw"(#{link_to 'reset', user_reset_api_key_path(current_user)})"
      
  %p
    %strong= link_to 'Back to Dashboard', dashboard_path